# Site settings
title: Jekyll Carousel Demo
description: A simple Jekyll site with an image carousel
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

include:
  - assets
  - assets/photos
  
keep_files: [assets]